#!/bin/bash
# 使用激光雷达SLAM生成地图的脚本

echo "=== 激光雷达SLAM建图指南 ==="
echo ""
echo "1. 确保已安装以下ROS2包："
echo "   - slam_toolbox"
echo "   - nav2_cartographer"
echo "   - cartographer_ros"
echo ""
echo "2. 安装命令："
echo "   sudo apt install ros-humble-slam-toolbox"
echo "   sudo apt install ros-humble-nav2-cartographer"
echo "   sudo apt install ros-humble-cartographer-ros"
echo ""
echo "3. 使用slam_toolbox建图："
echo "   # 创建建图launch文件"
echo "   mkdir -p ~/radar/hnurm_radar/slam_launch"
echo ""
echo "4. 建图步骤："
echo "   a) 启动雷达驱动"
echo "      ros2 launch livox_ros_driver2 rviz_HAP_launch.py"
echo ""
echo "   b) 启动SLAM建图节点"
echo "      ros2 launch slam_toolbox online_async_launch.py use_sim_time:=false"
echo ""
echo "   c) 在RViz中查看建图效果"
echo "   d) 控制机器人在环境中移动，覆盖整个区域"
echo ""
echo "   e) 保存地图"
echo "      ros2 run nav2_map_server map_saver_cli -f map_name"
echo ""
echo "5. 使用cartographer建图："
echo "   a) 启动雷达驱动"
echo "      ros2 launch livox_ros_driver2 rviz_HAP_launch.py"
echo ""
echo "   b) 启动cartographer"
echo "      ros2 launch cartographer_ros cartographer.launch.py"
echo ""
echo "   c) 保存地图"
echo "      ros2 run cartographer_ros cartographer_pbstream_to_ros_map -pbstream_map map.pbstream -map_topicmap"
echo ""
echo "6. 注意事项："
echo "   - 建图时保持机器人缓慢移动"
echo "   - 确保环境中有足够的特征点"
echo "   - 回环闭合对地图质量很重要"
echo "   - 建图完成后需要将地图转换为PCD格式"
echo ""
echo "7. 将ROS地图转换为PCD："
echo "   python3 -c \"
echo "   import numpy as np"
echo "   import open3d as o3d"
echo "   from nav_msgs.msg import OccupancyGrid"
echo "   import rclpy"
echo "   from rclpy.node import Node"
echo ""
echo "   # 需要订阅/map话题获取OccupancyGrid数据"
echo "   # 然后转换为点云并保存为PCD"
echo "   \""