/**:
  ros__parameters:
    pointcloud_sub_topic: "/lidar_pcds"
    pcd_file: "/home/rq/radar/hnurm_radar/normalized_map.pcd"
    downsampled_pcd_file_: "/home/rq/radar/hnurm_radar/normalized_map_downsample.pcd"
    generate_downsampled_pcd : false   # please turn this off when using registration
    num_threads: 7
    num_neighbors: 20
    max_dist_sq: 0.5
    source_voxel_size: 0.25
    map_voxel_size: 0.25

    use_fixed: true

    use_quatro: true
    #quatro params
    m_rotation_max_iter: 200
    m_num_max_corres: 100 
    m_normal_radius: 0.5 
    m_fpfh_radius: 1.2 
    m_distance_threshold: 30.0 
    m_noise_bound: 0.2 
    m_rotation_gnc_factor: 1.39 
    m_rotation_cost_thr: 0.0001 
    m_estimate_scale: false 
    m_use_optimized_matching: true 
